name: Build, Test, and Upload Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Install GCC and GCov
    - name: Install GCC and GCov 10
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
        sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-10 10

    # Step 3: Verify GCC and GCov Versions
    - name: Verify GCC and GCov Versions
      run: |
        gcc --version
        gcov --version

    # Step 4: Build Convert Executable
    - name: Build Convert Executable
      run: |
        make -f path/to/Makefile convert

    # Step 5: Upload Convert Executable
    - name: Upload Convert Executable
      uses: actions/upload-artifact@v4
      with:
        name: Convert Utility
        path: ./convert

    # Step 6: Build and Test with Coverage
    - name: Build and Test with Coverage
      run: |
        make -f path/to/Makefile ctest
        mkdir -p testing
        ./test_script > testing/test_results.txt
        for file in src/backend/2048_test_cases_files/*.c; do
          gcov -o src/backend/2048_test_cases_files "$file" > "testing/$(basename "$file").gcov.txt"
          grep -oP '\d+\.\d+% of' "testing/$(basename "$file").gcov.txt" | head -n 1 | sed 's/ of//' >> testing/coverage_summary.txt
        done

    # Step 7: Upload Test Results
    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: CTest
        path: ./testing/test_results.txt

    # Step 8: Upload Individual Coverage Reports
    - name: Upload Individual Coverage Reports
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Reports
        path: ./testing/*.gcov.txt

    # Step 9: Upload Coverage Summary
    - name: Upload Coverage Summary
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Summary
        path: ./testing/coverage_summary.txt
