name: Build, Test, and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Build the program
    - name: Build Convert
      run: |
        gcc -o 2048_test_cases -fprofile-arcs -ftest-coverage src/backend/2048_test_cases_files/2048_test_cases.c

    # Step 3: Upload the compiled program
    - name: Upload Convert
      uses: actions/upload-artifact@v4
      with:
        name: Executable
        path: ./2048_test_cases

    # Step 4: Build and run tests
    - name: Build Test and Capture Output
      run: |
        mkdir -p testing
        ./2048_test_cases > testing/test_results.txt
        gcov src/backend/2048_test_cases_files/2048_test_cases.c > testing/coverage_report.txt

    # Step 5: Upload test results
    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: ./testing/test_results.txt

    # Step 6: Upload coverage report
    - name: Upload Coverage Report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Report
        path: ./testing/coverage_report.txt
