name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GCC and Matching Gcov
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10

    - name: Configure GCC and Gcov
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
        sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-10 10

    - name: Check GCC and Gcov versions
      run: |
        gcc --version
        gcov --version

    - name: Compile the program with GCC-10
      run: |
        gcc-10 -o 2048_test_cases -fprofile-arcs -ftest-coverage src/backend/2048_test_cases_files/2048_test_cases.c

    - name: Run the test cases
      run: ./2048_test_cases

    - name: Generate coverage report
      run: |
        gcov-10 src/backend/2048_test_cases_files/2048_test_cases.c

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: 2048_test_cases

    - name: Upload coverage files
      uses: actions/upload-artifact@v3
      with:
        name: coverage-files
        path: |
          src/backend/2048_test_cases_files/*.gcov
          src/backend/2048_test_cases_files/*.gcda
          src/backend/2048_test_cases_files/*.gcno
          src/backend/2048_test_cases_files/*.c
