name: Build, Test, and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Debug Files and Paths
    - name: List Files
      run: |
        echo "Listing files in the repository root:"
        ls -R
        echo "Checking for 2048_test_cases.c:"
        ls src/backend/2048_test_cases_files

    # Step 3: Build the Program with Coverage
    - name: Build Program
      run: |
        gcc -o 2048_test_cases -fprofile-arcs -ftest-coverage src/backend/2048_test_cases_files/2048_test_cases.c

    # Step 4: Upload Executable
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: Executable
        path: ./2048_test_cases

    # Step 5: Run Tests
    - name: Run Tests
      run: |
        mkdir -p testing
        ./2048_test_cases > testing/test_results.txt || echo "Program crashed or returned non-zero exit code"

    # Step 6: Generate Test Cases for Sliding and Combining Tiles
    - name: Run Test Cases for Sliding and Combining Tiles
      run: |
        mkdir -p testing
        gcc -o test_cases -fprofile-arcs -ftest-coverage src/backend/2048_test_cases_files/2048_test_cases.c
        ./test_cases > testing/sliding_combining_test_results.txt || echo "Test cases crashed or returned non-zero exit code"

    # Step 7: Generate Coverage Report
    - name: Generate Coverage Report
      run: |
        mkdir -p testing
        gcov src/backend/2048_test_cases_files/2048_test_cases.c > testing/coverage_report.txt || echo "gcov failed"

    # Step 8: Upload Test Results
    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: ./testing/test_results.txt

    # Step 9: Upload Sliding and Combining Tiles Test Results
    - name: Upload Sliding and Combining Tiles Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Sliding and Combining Tiles Test Results
        path: ./testing/sliding_combining_test_results.txt

    # Step 10: Upload Coverage Report
    - name: Upload Coverage Report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Report
        path: ./testing/coverage_report.txt
