name: Build, Test, and Upload Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Build Convert Executable
    - name: Build Convert Executable
      run: |
        gcc -o convert src/backend/2048_test_cases_files/*.c

    # Step 3: Upload Convert Executable
    - name: Upload Convert Executable
      uses: actions/upload-artifact@v4
      with:
        name: Convert Executable
        path: ./convert

    # Step 4: Build and Test with Coverage
    - name: Build and Test with Coverage
      run: |
        gcc -o ctest --coverage src/backend/2048_test_cases_files/*.c
        mkdir -p testing
        ./ctest > testing/test_results.txt

        # Generate individual GCov reports and extract coverage percentages
        for file in src/backend/2048_test_cases_files/*.c; do
          gcov "$file" > "testing/$(basename "$file").gcov.txt"
          grep -oP '\d+\.\d+% of' "testing/$(basename "$file").gcov.txt" | head -n 1 | sed 's/ of//' >> testing/coverage_summary.txt
        done

    # Step 5: Upload Test Results
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: ./testing/test_results.txt

    # Step 6: Upload Individual Coverage Reports
    - name: Upload Individual Coverage Reports
      uses: actions/upload-artifact@v4
      with:
        name: Individual Coverage Reports
        path: ./testing/*.gcov.txt

    # Step 7: Upload Coverage Summary
    - name: Upload Coverage Summary
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Summary
        path: ./testing/coverage_summary.txt

    # Step 8: Upload Raw Coverage Files
    - name: Upload Raw Coverage Files
      uses: actions/upload-artifact@v4
      with:
        name: Raw Coverage Files
        path: |
          *.gcov
          *.gcda
          *.gcno
