name: Build, Test, and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Debug Files and Paths
    - name: List Files
      run: |
        echo "Listing files in the repository root:"
        ls -R
        echo "Checking for 2048_test_cases.c:"
        ls src/backend/2048_test_cases_files

    # Step 3: Build the Program
    - name: Build Program
      run: |
        mkdir -p testing
        gcc -o 2048_test_cases -fprofile-arcs -ftest-coverage src/backend/2048_test_cases_files/2048_test_cases.c

    # Step 4: Upload Executable
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: Executable
        path: ./2048_test_cases

    # Step 5: Run Tests
    - name: Run Tests
      run: |
        ./2048_test_cases > testing/test_results.txt || echo "Program crashed or returned non-zero exit code"

    # Step 6: Generate Coverage Report
    - name: Generate Coverage Report
      run: |
        gcov src/backend/2048_test_cases_files/2048_test_cases.c > testing/coverage_report.txt || echo "gcov failed"
        echo "Coverage report contents:"
        cat testing/coverage_report.txt

    # Step 7: Debug Generated Files
    - name: List Generated Files
      run: |
        echo "Listing all files in the testing directory:"
        ls -al testing

    # Step 8: Upload Test Results
    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: testing/test_results.txt

    # Step 9: Upload Coverage Report
    - name: Upload Coverage Report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Report
        path: testing/coverage_report.txt

    # Step 10: Upload Individual Test Reports (Optional)
    - name: Upload Sliding and Combining Tiles Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Sliding and Combining Tiles Test Results
        path: testing/sliding_combining_tiles_test_results.txt
