name: Build, Test, and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Build Convert
    - name: Build Convert
      run: make convert

    # Step 3: Upload Executable
    - name: Upload Convert
      uses: actions/upload-artifact@v4
      with:
        name: Convert Utility
        path: ./convert

    # Step 4: Build and Run Tests
    - name: Build Test
      run: |
        make ctest
        cd testing
        ./test_script > test_results.txt
        gcov ../src/backend/2048_test_cases_files/2048_test_cases.c > coverage_report.txt

    # Step 5: Upload Test Results
    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: CTest
        path: ./testing/test_results.txt

    # Step 6: Upload Coverage Report
    - name: Upload Coverage Report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Report
        path: ./testing/coverage_report.txt
