name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Build the program
    - name: Build Program
      run: |
        gcc -o 2048_test_cases -fprofile-arcs -ftest-coverage src/backend/2048_test_cases_files/2048_test_cases.c

    # Step 3: Run the program to generate coverage data
    - name: Run Tests
      run: ./2048_test_cases

    # Step 4: Generate coverage report
    - name: Generate Coverage Report
      run: |
        gcov src/backend/2048_test_cases_files/2048_test_cases.c -o .

    # Step 5: Upload Executable as Artifact
    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: 2048_test_cases

    # Step 6: Upload Coverage Files as Artifacts
    - name: Upload Coverage Files
      uses: actions/upload-artifact@v3
      with:
        name: coverage-files
        path: |
          *.gcov
          *.gcda
          *.gcno
