name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Build in Docker
      uses: docker://gcc:9
      with:
        entrypoint: ""
      run: |
        apt-get update
        apt-get install -y gcov
        gcc --version
        gcov --version
        gcc -o 2048_test_cases -fprofile-arcs -ftest-coverage src/backend/2048_test_cases_files/2048_test_cases.c
        ./2048_test_cases
        gcov src/backend/2048_test_cases_files/2048_test_cases.c

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: 2048_test_cases

    - name: Upload coverage files
      uses: actions/upload-artifact@v3
      with:
        name: coverage-files
        path: |
          src/backend/2048_test_cases_files/*.gcov
          src/backend/2048_test_cases_files/*.gcda
          src/backend/2048_test_cases_files/*.gcno
