name: Build, Test, and Upload Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Install GCC and Coverage Tools
    - name: Install GCC with Coverage Support
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ lcov

    # Step 3: Build Program with Coverage
    - name: Build Program
      run: |
        mkdir -p testing
        gcc -o 2048_test_cases -fprofile-arcs -ftest-coverage src/backend/2048_test_cases_files/2048_test_cases.c

    # Step 4: Run Program
    - name: Run Program
      run: |
        ./2048_test_cases > testing/test_results.txt || echo "Program crashed or returned non-zero exit code"

    # Step 5: Generate Coverage Report
    - name: Generate Coverage Report
      run: |
        gcov src/backend/2048_test_cases_files/2048_test_cases.c > testing/coverage_report.txt || echo "gcov failed"
        # Append Coverage Percentage to Report
        coverage=$(grep -oP '\d+\.\d+%' testing/coverage_report.txt | head -n 1)
        echo "Coverage Percentage: $coverage" >> testing/coverage_report.txt

    # Step 6: Upload Coverage Report Artifact
    - name: Upload Coverage Report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Report
        path: ./testing/coverage_report.txt
